spring:
  application:
    name: sbms
  profiles:
    active: dev
#  mvc.throw-exception-if-no-handler-found: true
#  resources.add-mappings:

server:
  port: 8080

logging:
  config: ./config/logback-spring.xml

